---

- name: install unzip
  ansible.builtin.package:
    name: unzip
  become: yes

- name: 'create cache directory {{ rclone_binary_install_cache_dir }}'
  ansible.builtin.file:
    path: '{{ rclone_binary_install_cache_dir }}'
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: yes

- name: 'download rclone from {{ __rclone_github_download_url }}'
  ansible.builtin.get_url:
    url: '{{ __rclone_github_download_url }}'
    dest: '{{ __rclone_binstall_cache_path }}'
    owner: root
    group: root
    mode: '0644'
  become: yes
  check_mode: no

- name: 'extract {{ __rclone_binstall_cache_path }}'
  ansible.builtin.unarchive:
    remote_src: yes
    src: '{{ __rclone_binstall_cache_path }}'
    dest: '{{ rclone_binary_install_cache_dir }}'
    owner: root
    group: root
    mode: '0755'
  become: yes
  check_mode: no

- name: 'create bin directory {{ rclone_binary_install_bin_dir }}'
  ansible.builtin.file:
    path: '{{ rclone_binary_install_bin_dir }}'
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: yes

- name: 'install to {{ __rclone_binstall_path }}'
  ansible.builtin.copy:
    remote_src: yes
    src: '{{ __rclone_binstall_extract_path }}'
    dest: '{{ __rclone_binstall_path }}'
    owner: root
    group: root
    mode: '0755'
  become: yes

...
