---

dependency:
  name: galaxy

driver:
  name: docker

platforms:

  - name: centos-7
    image: geerlingguy/docker-centos7-ansible
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: yes
    pre_build_image: yes

  - name: centos-8
    image: geerlingguy/docker-centos8-ansible
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: yes
    pre_build_image: yes

  - name: rocky-8
    image: geerlingguy/docker-rockylinux8-ansible
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: yes
    pre_build_image: yes

  - name: rocky-9
    image: geerlingguy/docker-rockylinux9-ansible
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: yes
    pre_build_image: yes

provisioner:
  name: ansible

verifier:
  name: ansible

...
