---

provisioner:
  playbooks:
    converge: ../default/converge.yml
  name: ansible
  inventory:
    group_vars:
      all:
        rclone_version: 1.64.2
        rclone_binary_install_bin_dir: /opt/usr/local/bin
        rclone_binary_install_cache_dir: /opt/var/cache

...
