---

dependency:
  name: galaxy

driver:
  name: docker

platforms:

  - name: archlinux
    image: ghcr.io/idiv-biodiversity/ansible-molecule-archlinux:latest
    pre_build_image: yes
    groups:
      - nosudo

  - name: rockylinux-9
    image: ghcr.io/idiv-biodiversity/ansible-molecule-rockylinux-9:latest
    pre_build_image: yes
    groups:
      - nosudo

provisioner:
  name: ansible
  inventory:
    group_vars:
      nosudo:
        ansible_become_method: su

verifier:
  name: ansible

...
